---
# Переменные для мониторинга
zabbix_server_version: '7.0'
zabbix_db_host: "localhost"
zabbix_db_name: "zabbix"
zabbix_db_user: "zabbix"
zabbix_db_password: "zabbix_password_123"
zabbix_php_timezone: "Europe/Moscow"

zabbix_services:
  - zabbix-server
  - zabbix-agent
  - apache2